### PR TITLE
Updating documentation

### PR DESCRIPTION
**Pull request by adilansari**
- Documentation was broken, just making a quick fix for that.
- We are not using default category properly, I will post a refactored code sometime soon.

@mwhooker

### CODE REVIEW

**Comment by adilansari** [comment]
Hi @mwhooker would you mind if I take over this project on pypi?

**Comment by mwhooker** [comment]
I'll xfer tonight. What's your username

**Comment by adilansari** [comment]
`adilansari`
Thanks

**Comment by mwhooker** [comment]
Should be done. let me know if you have any issues

-- 
Matthew Hooker

On April 30, 2015 at 3:51:07 PM, Adil Ansari (notifications@github.com) wrote:

adilansari

**Pull request closed without merging**
